version: "3.9"
services:
  mock-fhir:
    build: ./services/mock-fhir
    ports: ["8080:8080"]

  mcp-server:
    build: ./services/mcp-server
    environment:
      SAFE_MODE: "true"
      TASK_DB_PATH: "/data/tasks.db"
    ports: ["9000:9000"]
    depends_on: [mock-fhir]
    volumes:
      - tasks-data:/data

  fhir-listener:
    build: ./services/fhir-listener
    environment:
      MCP_URL: "http://mcp-server:9000/mcp"
    ports: ["7001:7001"]
    depends_on: [mcp-server]

  tasks-api:
    build: ./services/tasks-api
    environment:
      TASK_DB_PATH: "/data/tasks.db"
    ports: ["7100:7100"]
    depends_on: [mcp-server]
    volumes:
      - tasks-data:/data

volumes:
  tasks-data:
