version: "3.9"
services:
  mock-fhir:
    build: ./services/mock-fhir
    ports: ["8080:8080"]

  mcp-server:
    build: ./services/mcp-server
    environment:
      # In Azure, use MI + real endpoints. Here: stubbed.
      # SQL / Event Grid calls are no-ops in this starter.
      PLACEHOLDER: "true"
    ports: ["9000:9000"]
    depends_on: [mock-fhir]

  fhir-listener:
    build: ./services/fhir-listener
    environment:
      MCP_URL: "http://mcp-server:9000/mcp"
    ports: ["7001:7001"]
    depends_on: [mcp-server]
